import React from 'react';
import { Image as ImageIcon, Loader2, Sparkles, Download } from 'lucide-react';
import { motion } from 'framer-motion';
import AutoCorrectingTextarea from './AutoCorrectingTextarea';
import { ImageGeneratorState } from '../types';

interface ImageGeneratorProps {
  state: ImageGeneratorState;
  setState: React.Dispatch<React.SetStateAction<ImageGeneratorState>>;
  onGenerate: () => void;
}

const LoadingState = () => (
    <div className="absolute inset-0 bg-[var(--bg-card)]/80 flex flex-col justify-center items-center gap-4 transition-opacity duration-300 z-10">
        <Loader2 className="w-12 h-12 text-[var(--accent-color-1)] animate-spin" />
        <p className="text-lg text-[var(--text-primary)] font-medium">Generating your masterpiece...</p>
        <p className="text-sm text-[var(--text-secondary)]">This can take a moment.</p>
    </div>
);

const ImageGenerator: React.FC<ImageGeneratorProps> = ({ state, setState, onGenerate }) => {
  const { prompt, isLoading, imageUrl, error } = state;

  const handleKeyPress = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      onGenerate();
    }
  };

  const setPrompt = (newPrompt: string) => {
    setState(prev => ({ ...prev, prompt: newPrompt }));
  };

  return (
    <div className="flex flex-col h-full p-4 md:p-6 overflow-y-auto">
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-2 gap-6 h-full">
        <div className="bg-[var(--bg-card)] border border-[var(--border-primary)] rounded-2xl p-6 flex flex-col gap-4 shadow-2xl shadow-[var(--shadow-color)]">
          <h3 className="text-lg font-semibold text-[var(--text-primary)]">Create Your Image</h3>
          <p className="text-[var(--text-secondary)] text-sm">Describe the image you want to create. Be as detailed as you like for the best results!</p>
          <AutoCorrectingTextarea
            value={prompt}
            setValue={setPrompt}
            onKeyPress={handleKeyPress}
            placeholder="e.g., A majestic crystal palace on a floating island, surrounded by glowing waterfalls, digital art"
            className="flex-1 w-full bg-[var(--bg-input)] border border-[var(--border-secondary)] rounded-xl p-3 text-[var(--text-primary)] focus:ring-2 focus:ring-[var(--accent-color-1)] focus:outline-none transition-all resize-none placeholder:text-[var(--text-secondary)]"
            containerClassName="flex-1 min-h-[150px] md:min-h-0"
            rows={6}
            disabled={isLoading}
          />
          <button
            onClick={onGenerate}
            disabled={isLoading || !prompt.trim()}
            className="w-full flex items-center justify-center gap-2 bg-[var(--bg-button-primary)] text-[var(--text-button-primary)] p-3 rounded-xl disabled:opacity-50 disabled:cursor-not-allowed hover:bg-[var(--bg-button-primary-hover)] transition-all font-semibold shadow-lg hover:shadow-[var(--shadow-color-accent)]"
          >
            <Sparkles className="w-5 h-5"/>
            Generate Image
          </button>
        </div>
        <div className="bg-[var(--bg-card)]/50 border-2 border-dashed border-[var(--border-primary)] rounded-2xl p-4 relative flex justify-center items-center min-h-[300px] lg:min-h-0">
          {isLoading && <LoadingState />}
          {error && <p className="text-red-500">{error}</p>}
          {!isLoading && !imageUrl && !error && (
            <div className="text-center text-[var(--text-secondary)]">
              <ImageIcon className="w-16 h-16 mx-auto mb-2 text-[var(--accent-color-1)]" />
              <p className="font-medium text-[var(--text-primary)]">Your generated image will appear here.</p>
              <p className="text-sm">Let your creativity flow!</p>
            </div>
          )}
          {imageUrl && (
            <div className="relative group w-full h-full flex justify-center items-center">
                <motion.img 
                  initial={{ scale: 0.95, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  transition={{ duration: 0.3 }}
                  src={imageUrl} 
                  alt="Generated by PAL AI" 
                  className="max-w-full max-h-full object-contain rounded-lg shadow-2xl"
                />
                 <a 
                    href={imageUrl} 
                    download="pal-ai-generated-image.png"
                    className="absolute bottom-4 right-4 bg-[var(--bg-button-primary)] text-[var(--text-button-primary)] p-2.5 rounded-full hover:bg-[var(--bg-button-primary-hover)] transition-all shadow-lg hover:shadow-[var(--shadow-color-accent)] opacity-0 group-hover:opacity-100"
                    aria-label="Download Image"
                    title="Download Image"
                >
                    <Download className="w-5 h-5" />
                </a>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ImageGenerator;
